In [ ]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time


mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar cascade files\haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar cascade files\haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar cascade files\haarcascade_righteye_2splits.xml')



lbl=['Close','Open']

model = load_model('models/cnncat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(gray)
    right_eye =  reye.detectMultiScale(gray)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred = model.predict(r_eye)
        print(rpred)
        if(rpred[0][0]==1):
            lbl='Open' 
        if(rpred[0][0]==0):
            lbl='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(24,24,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred = model.predict(l_eye)
        #print(lpred)
        if(lpred[0][0]==1):
            
            lbl='Open'   
        if(lpred[0][0]>=1):
            lbl='Closed'
        break

    if(rpred[0][1]<=0.9 and lpred[0][1]<=0.9):  #right close score increases
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    # if(rpred[0]==1 or lpred[0]==1):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0 
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>15):
        # if person feeling sleepy beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
            
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
[[0.03628426 0.9637158 ]]
[[0.01366978 0.9863302 ]]
[[0.00262493 0.99737513]]
[[0.00299477 0.9970053 ]]
[[0.00683705 0.993163  ]]
[[0.00173072 0.9982693 ]]
[[0.00334457 0.99665546]]
[[0.00376734 0.9962327 ]]
[[0.9989235  0.00107651]]
[[0.00428579 0.9957141 ]]
[[0.13421339 0.8657866 ]]
[[0.00534489 0.99465513]]
[[3.6967034e-04 9.9963033e-01]]
[[9.7898976e-04 9.9902105e-01]]
[[0.00269668 0.99730325]]
[[0.00284627 0.99715376]]
[[0.00218504 0.9978149 ]]
[[0.00484007 0.9951599 ]]
[[0.00283295 0.99716705]]
[[0.00132722 0.99867284]]
[[0.00296002 0.99704   ]]
[[0.00516241 0.9948376 ]]
[[0.03327011 0.9667299 ]]
[[0.01513976 0.98486024]]
[[0.04901728 0.9509827 ]]
[[0.00977144 0.99022853]]
[[0.01258922 0.98741084]]
[[0.01349161 0.98650837]]
[[0.00704862 0.99295133]]
[[9.990815e-01 9.184911e-04]]
[[0.99781466 0.00218534]]
[[0.10167913 0.89832085]]
[[0.00326992 0.9967301 ]]
[[0.02848414 0